[package]
name = "stream_resp"
version = "0.1.0"
edition = "2021"
authors = ["HanLin Chai <take3812@gmail.com>"]
description = "StreamRESP is a RESP (Redis Serialization Protocol) parser implemented using a finite state machine (FSM) approach. Designed for streaming scenarios."
license = "MIT"

[dependencies]
bytes = "1.8.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false
panic = "abort"
strip = true
